config/routes.rb
Rails.application.routes.draw do
  get 'dashboard' => 'dashboard#home'
  get 'new/article' => 'dashboard#new_article'
  devise_for :users
  root 'page#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #:confirmable, :lockable,:timeoutable,:omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render 'dashboard/article/new_article'
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
  end

  def articles
    @articles = Article.all
  end

  def new_article
    @article = Article.new
    render 'dashboard/article/new_article'
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/dashboard/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a href="">#Stats</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li class="active"><a href="#">Articles</a></li>
    <li>
      <%= link_to "New", new_article_path, method: :get %>
    </li>
    <li><a href="#">#Drafts</a></li>
    <li><a href="#">#Trash</a></li>
  </ul>
</div>

app/views/dashboard/article/new_article.erb
<div class="container-fluid">
  <div class="row">
    <%= render 'dashboard/sidebar' %>
    <div class="col-sm-9 col-sm-offset-3 col-md-offset-2 main">
      <%= form_for @article, url: articles_path do |article| %>
          <div class="form-group">
            <%= article.label 'Title' %>
            <%= article.text_field :title, :class => 'form-control' %>
          </div>
          <div class="form-group">
            <%= article.label 'Description' %>
            <%= article.text_area :body, :class => 'form-control', :rows => "10" %>
          </div>
          <%= article.button "Publish", :class => "btn btn-success" %>
          <%= %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/home.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render 'sidebar' %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        WELL PLAYED
      </a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <% @articles.each do |article| %>
          <h1><%= article.title %></h1>

          <p>
            <%= article.body %>
          </p>

      <% end %>
    </div>
  </div>
</div>